### ISSUE TITLE
problem with uberdog server on win32

### ISSUE THREAD

**Issue by facehunter2003** [FluffyCrimsonFox/Toontown-Evolution#7]
Dear Crimson Fox,

I have found an issue while trying to start the server on a windows client. I have gotten all of the servers to connect to each other except the uberdog one. It spews out errors, errors below (bolded are what the issue I think is), this problem might be the fact that I didn't clone it (with the .git link) and github probably ignored important files when I downloaded the .zip version of the file, as that's what I heard it does sometimes.

Have a nice day -Face

"

Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 162, in _run_module_as_main

    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "G:\Non-SteamGames\Toontown-Evolution-master\src\toontown\uberdog\Service
Start.py", line 41, in <module>
    config.GetInt('air-stateserver', 4002))
  File "toontown\uberdog\ToontownUberRepository.py", line 21, in __init__
    ToontownInternalRepository.__init__(self, baseChannel, serverId, dcSuffix='U
D')
  File "toontown\distributed\ToontownInternalRepository.py", line 12, in __init_
_
    dcSuffix=dcSuffix, connectMethod=connectMethod, threadedNet=threadedNet)
  File "C:\Panda3D-1.10.0\direct\distributed\AstronInternalRepository.py", line
139, in __init__
    self.readDCFile(dcFileNames)
  File "C:\Panda3D-1.10.0\direct\distributed\ConnectionRepository.py", line 311,
 in readDCFile
    self.importModule(dcImports, moduleName, importSymbols)
  File "C:\Panda3D-1.10.0\direct\distributed\ConnectionRepository.py", line 408,
 in importModule
    module = __import__(moduleName, globals(), locals(), importSymbols)
  File "toontown\uberdog\ClientServicesManagerUD.py", line 1, in <module>
    import semidbm
**ImportError: No module named semidbm**
Warning: pandac.PandaModules is deprecated, **import from panda3d.core instead**
TTLocalizer: Running in language: english
OTPLocalizer: Running in language: english
DCFile::read of astron/dclass/otp.dc
DCFile::read of astron/dclass/toon.dc

"

**Comment by FluffyCrimsonFox** [comment]
you're supposed to use the Panda3D that comes with the game

**Comment by facehunter2003** [comment]
Oh yeah sorry didn't see that in the log, thanks for noticing that. I would've been clueless the whole time. I'll see if that works.

**Comment by facehunter2003** [comment]
Worked. I thought it was already the base Panda3D 10.0 so I just hooked it to the one on the main drive I was using. Thanks again.
